[package]
name = "NightE"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.32"
colored = "3.0.0"
log = "0.4.26"
rocket = { version = "0.5.1", features = ["json"] }
tokio = { version = "1.44.1", features = ["full"] }
